---
- name: Configure Jellyfin ports
  xml:
    path: /etc/jellyfin/system.xml
    xpath: /ServerConfiguration/{{ item.key }}
    value: "{{ item.value }}"
  loop:
    - key: PublicPort
      value: "{{ jellyfin_HTTP_port | string }}"
    - key: PublicHttpsPort
      value: "{{ jellyfin_HTTPS_port | string }}"
    - key: HttpServerPortNumber
      value: "{{ jellyfin_HTTP_port | string }}"
    - key: HttpsPortNumber
      value: "{{ jellyfin_HTTPS_port | string }}"
  notify: Restart Jellyfin
- name: Configure Jellyfin networking
  ansible.builtin.xml:
    path: /etc/jellyfin/network.xml
    xpath: /NetworkConfiguration/{{ item.key }}/string
    value: "{{ item.value }}"
  loop:
    - key: LocalNetworkAddresses
      value: "{{ jellyfin_bind_ip }}"
  when: jellyfin_bind_ip is defined
  notify: Restart Jellyfin
...
