---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: debian-stretch
    image: minimum2scp/systemd-stretch
    privileged: true
    command: /sbin/init

  - name: debian-buster
    image: minimum2scp/systemd-buster
    privileged: true
    command: /sbin/init

  - name: ubuntu-bionic
    image: jrei/systemd-ubuntu:18.04
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
...
